# Generated by Django 3.1.2 on 2020-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="photo",
            field=models.ImageField(blank=True, upload_to="authors"),
        ),
        migrations.AddField(
            model_name="book",
            name="photo",
            field=models.ImageField(blank=True, upload_to="books"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(related_name="author", to="app.Author"),
        ),
    ]
