# Generated by Django 3.1.2 on 2020-10-09 16:42

import app.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20201009_1941"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=0,
                size=[500, 300],
                upload_to=app.models.get_file_path,
            ),
        ),
    ]
